{
  "config": {
    "step": {
      "user": {
        "data": {
          "username": "Account",
          "password": "Password",
          "mobile_app": "Mobile app",
          "advanced_settings": "Advanced settings"
        },
        "description": "Please enter username and password that you use to connect with the selected Midea mobile application.",
        "title": "Sign-in with Midea app account"
      },
      "advanced_settings": {
        "data": {
          "username": "Account",
          "password": "Password",
          "appkey": "Mobile app key",
          "appid": "Mobile app id",
          "network_range": "Appliance address or network range",
          "use_cloud": "Use cloud API to poll devices"
        },
        "description": "You can provide specific Midea mobile app key and app id if the default ones don't work.\n\nYou can also specify network address (e.g. 192.0.1.2) or range (e.g. 192.0.3.4/24) to search for specific appliance(s) if regular discovery doesn't work.",
        "title": "Advanced settings"
      },
      "unreachable_appliance": {
        "data": {
          "ip_address": "IPv4 address",
          "name": "Device name",
          "token": "Token",
          "token_key": "Token key",
          "ignore_appliance": "Ignore this appliance",
          "use_cloud": "Use cloud API to poll this device"
        },
        "description": "We were unable to discover an appliance called {name} with the id {id} on the local network.\n\nIf you know appliance's IPv4 address, please enter it below to add it to Home Assistant.\n\nYou can also provide token and key if you have them. If not, we will obtain them from Midea cloud.",
        "title": "Appliance IPv4 address is missing"
      },
      "reauth_confirm": {
        "data": {
          "username": "Account",
          "password": "Password",
          "appkey": "Mobile app key",
          "appid": "Mobile app id",
          "network_range": "Appliance address or network range"
        },
        "title": "[%key:common::config_flow::title::reauth%]",
        "description": "The Midea dehumidifier (LAN) integration needs to re-authenticate your account"
      }
    },
    "error": {
      "cannot_connect": "Unnable to connect to appliance ({cause}).",
      "connection_error": "Connection error ({cause}).",
      "invalid_app_name": "Unsupported application name ({cause}). See log for more information.",
      "invalid_appkey": "Please provide Midea mobile app key and app id",
      "invalid_auth": "Invalid username or password ({cause})",
      "invalid_ip_address": "Invalid IPv4 address ({cause}), please enter a valid IPv4 address (e.g. 192.0.1.2)",
      "invalid_ip_range": "Invalid IPv4 network address or network range ({cause}). Expected formats are 192.0.1.2 or 192.0.3.4/24",
      "invalid_state": "Unexpected state of configuration flow. See log for more information.",
      "no_cloud": "Unable to connect to Midea cloud API",
      "not_discovered": "Unable to find appliance at specified IPv4 address.",
      "unknown": "An unknown error has occurred. See log for more information."
    },
    "abort": {
      "single_instance_allowed": "Already defined a Midea app account. Only a single account is supported for Midea dehumidifier (LAN).",
      "reauth_successful": "Re-authentication was successful"
    }
  }
}